Updated CI/CD workflow.

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -58,10 +58,18 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
 
+      - name: Debug SSH Setup
+        run: |
+          whoami
+          pwd
+          ls -lah ~/
+          mkdir -p ~/.ssh || (echo "Failed to create .ssh directory" && exit 1)
+          ls -lah ~/.ssh
+
       - name: Set Up SSH Key
         run: |
           mkdir -p ~/.ssh
-          echo -e "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
+          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
           ssh-keyscan -H 13.53.200.254 >> ~/.ssh/known_hosts
 
